import { Worker, Company, WorkerRequest, AttendanceRecord, PaymentRecord, AppNotification } from './types';

export const INITIAL_WORKERS: Worker[] = [
  {
    id: 'WKR-1001',
    fullName: 'Ramesh Kumar',
    photoUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=400&auto=format&fit=crop&q=80',
    phoneNumber: '+91 98765 43210',
    aadhaarNumber: 'XXXX-XXXX-4921',
    village: 'Rampur',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    skill: 'Construction',
    subSkill: 'Mason / Bricklayer',
    experienceYears: 6,
    languages: ['Hindi', 'Bhojpuri'],
    dailyWage: 850,
    availability: true,
    emergencyContact: {
      name: 'Sunita Devi',
      relationship: 'Wife',
      phone: '+91 98765 99881',
    },
    notes: 'Registered physically at admin office.',
    rating: 5.0,
    completedJobs: 0,
    currentStatus: 'Available',
    verificationStatus: 'Verified',
    documents: {
      photo: true,
      aadhaarCard: true,
      certificates: true,
    },
    registeredAt: '2026-08-01',
  },
  {
    id: 'WKR-1002',
    fullName: 'Suresh Patel',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    phoneNumber: '+91 91234 56789',
    aadhaarNumber: 'XXXX-XXXX-8812',
    village: 'Kheda',
    district: 'Ahmedabad',
    state: 'Gujarat',
    skill: 'Electrical',
    subSkill: 'Industrial Wiring Technician',
    experienceYears: 8,
    languages: ['Gujarati', 'Hindi'],
    dailyWage: 1100,
    availability: true,
    emergencyContact: {
      name: 'Bhavesh Patel',
      relationship: 'Brother',
      phone: '+91 91234 88776',
    },
    notes: 'Certified electrician.',
    rating: 5.0,
    completedJobs: 0,
    currentStatus: 'Available',
    verificationStatus: 'Verified',
    documents: {
      photo: true,
      aadhaarCard: true,
      certificates: true,
    },
    registeredAt: '2026-08-01',
  },
  {
    id: 'WKR-1003',
    fullName: 'Mohammad Imran',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    phoneNumber: '+91 97654 32109',
    aadhaarNumber: 'XXXX-XXXX-3341',
    village: 'Chandausi',
    district: 'Sambhal',
    state: 'Uttar Pradesh',
    skill: 'Plumbing',
    subSkill: 'Pipe Fitter / Drainage Specialist',
    experienceYears: 5,
    languages: ['Hindi', 'Urdu'],
    dailyWage: 900,
    availability: true,
    emergencyContact: {
      name: 'Fatima Begum',
      relationship: 'Mother',
      phone: '+91 97654 11223',
    },
    notes: 'Plumbing specialist.',
    rating: 5.0,
    completedJobs: 0,
    currentStatus: 'Available',
    verificationStatus: 'Verified',
    documents: {
      photo: true,
      aadhaarCard: true,
      certificates: true,
    },
    registeredAt: '2026-08-02',
  },
  {
    id: 'WKR-1004',
    fullName: 'Vikram Singh',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    phoneNumber: '+91 95432 10987',
    aadhaarNumber: 'XXXX-XXXX-9012',
    village: 'Bhiwani',
    district: 'Bhiwani',
    state: 'Haryana',
    skill: 'Welding',
    subSkill: 'ARC & TIG Structural Welder',
    experienceYears: 7,
    languages: ['Haryanvi', 'Hindi'],
    dailyWage: 1200,
    availability: true,
    emergencyContact: {
      name: 'Balwan Singh',
      relationship: 'Father',
      phone: '+91 95432 66554',
    },
    notes: 'ARC & TIG welder.',
    rating: 5.0,
    completedJobs: 0,
    currentStatus: 'Available',
    verificationStatus: 'Verified',
    documents: {
      photo: true,
      aadhaarCard: true,
      certificates: true,
    },
    registeredAt: '2026-08-02',
  }
];

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'CMP-2001',
    companyName: 'L&T Infrastructure Construtec Ltd',
    gstNumber: '07AAAAA0000A1Z5',
    industry: 'Construction & Civil Works',
    officeAddress: 'Sector 62, Cyber Park, Noida, UP - 201309',
    contactPerson: 'Vikrant Deshmukh (HR Head)',
    phone: '+91 98112 34567',
    email: 'hr@ltconst.com',
    status: 'Active',
    subscriptionPlan: 'Enterprise',
    hiringHistoryCount: 0,
    totalSpent: 0,
    joinedDate: '2026-08-01',
  },
  {
    id: 'CMP-2002',
    companyName: 'BuildCon Logistics & Warehousing',
    gstNumber: '09BBBBA1111B2Z8',
    industry: 'Logistics & Supply Chain',
    officeAddress: 'Expressway Hub, Greater Noida, UP',
    contactPerson: 'Megha Singhania',
    phone: '+91 98776 54321',
    email: 'hiring@buildcon.in',
    status: 'Active',
    subscriptionPlan: 'Pro',
    hiringHistoryCount: 0,
    totalSpent: 0,
    joinedDate: '2026-08-02',
  }
];

export const INITIAL_REQUESTS: WorkerRequest[] = [
  {
    id: 'REQ-5001',
    companyId: 'CMP-2001',
    companyName: 'L&T Infrastructure Construtec Ltd',
    skillRequired: 'Construction',
    subSkill: 'Mason / Bricklayer',
    numberOfWorkers: 5,
    assignedWorkerIds: [],
    location: 'Metro Site Phase 4, Botanical Garden, Noida',
    reportingDate: '2026-08-10',
    reportingTime: '08:00 AM',
    durationDays: 14,
    dailyWageOffered: 900,
    foodProvided: true,
    accommodationProvided: true,
    transportationProvided: true,
    genderPreference: 'Any',
    experienceRequiredYears: 4,
    remarks: 'Safety helmets mandatory.',
    priority: 'Normal',
    workflowStatus: 'Pending',
    createdAt: '2026-08-05',
  }
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [];

export const INITIAL_PAYMENTS: PaymentRecord[] = [];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [];

export const SKILL_CATEGORIES = [
  { name: 'Construction', subSkills: ['Mason / Bricklayer', 'Concrete Finisher', 'Scaffolder', 'Bar Bender / Steel Fixer'] },
  { name: 'Electrical', subSkills: ['Industrial Wiring Technician', 'Substation Operator', 'Cable Jointer', 'Maintenance Electrician'] },
  { name: 'Plumbing', subSkills: ['Pipe Fitter / Drainage Specialist', 'Sanitary Installer', 'Firefighting Pipeline Fitter'] },
  { name: 'Welding', subSkills: ['ARC & TIG Structural Welder', 'MIG Welder', 'Pipeline Gas Welder'] },
  { name: 'Carpentry', subSkills: ['Shuttering & Formwork Specialist', 'Furniture Woodworker', 'Interior Decorator'] },
  { name: 'Logistics', subSkills: ['Warehouse Loader / Forklift Operator', 'Packer & Dispatch Assistant', 'Inventory Helper'] }
];
