import { Worker, Company, WorkerRequest, AttendanceRecord, PaymentRecord, AppNotification } from './types';

export const INITIAL_WORKERS: Worker[] = [
  {
    id: 'WKR-1001',
    fullName: 'Ramesh Kumar',
    photoUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=400&auto=format&fit=crop&q=80',
    phoneNumber: '+91 98765 43210',
    aadhaarNumber: 'XXXX-XXXX-4921',
    village: 'Rampur',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    skill: 'Construction',
    subSkill: 'Mason / Bricklayer',
    experienceYears: 6,
    languages: ['Hindi', 'Bhojpuri'],
    dailyWage: 850,
    availability: true,
    emergencyContact: {
      name: 'Sunita Devi',
      relationship: 'Wife',
      phone: '+91 98765 99881',
    },
    notes: 'Highly experienced in RCC framing and brickwork. Punctual.',
    rating: 4.8,
    completedJobs: 42,
    currentStatus: 'Available',
    verificationStatus: 'Verified',
    documents: {
      photo: true,
      aadhaarCard: true,
      certificates: true,
    },
    registeredAt: '2025-01-12',
  },
  {
    id: 'WKR-1002',
    fullName: 'Suresh Patel',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    phoneNumber: '+91 91234 56789',
    aadhaarNumber: 'XXXX-XXXX-8812',
    village: 'Kheda',
    district: 'Ahmedabad',
    state: 'Gujarat',
    skill: 'Electrical',
    subSkill: 'Industrial Wiring Technician',
    experienceYears: 8,
    languages: ['Gujarati', 'Hindi', 'Basic English'],
    dailyWage: 1100,
    availability: false,
    emergencyContact: {
      name: 'Bhavesh Patel',
      relationship: 'Brother',
      phone: '+91 91234 88776',
    },
    notes: 'Certified electrician for commercial power distribution.',
    rating: 4.9,
    completedJobs: 65,
    currentStatus: 'Assigned',
    verificationStatus: 'Verified',
    documents: {
      photo: true,
      aadhaarCard: true,
      certificates: true,
    },
    registeredAt: '2024-11-05',
  },
  {
    id: 'WKR-1003',
    fullName: 'Mohammad Imran',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    phoneNumber: '+91 97654 32109',
    aadhaarNumber: 'XXXX-XXXX-3341',
    village: 'Chandausi',
    district: 'Sambhal',
    state: 'Uttar Pradesh',
    skill: 'Plumbing',
    subSkill: 'Pipe Fitter / Drainage Specialist',
    experienceYears: 5,
    languages: ['Hindi', 'Urdu'],
    dailyWage: 900,
    availability: true,
    emergencyContact: {
      name: 'Fatima Begum',
      relationship: 'Mother',
      phone: '+91 97654 11223',
    },
    notes: 'Specializes in high-rise building PVC & GI pipeline installation.',
    rating: 4.7,
    completedJobs: 29,
    currentStatus: 'Available',
    verificationStatus: 'Verified',
    documents: {
      photo: true,
      aadhaarCard: true,
      certificates: false,
    },
    registeredAt: '2025-02-01',
  },
  {
    id: 'WKR-1004',
    fullName: 'Vikram Singh',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    phoneNumber: '+91 95432 10987',
    aadhaarNumber: 'XXXX-XXXX-9012',
    village: 'Bhiwani',
    district: 'Bhiwani',
    state: 'Haryana',
    skill: 'Welding',
    subSkill: 'ARC & TIG Structural Welder',
    experienceYears: 7,
    languages: ['Haryanvi', 'Hindi'],
    dailyWage: 1200,
    availability: true,
    emergencyContact: {
      name: 'Balwan Singh',
      relationship: 'Father',
      phone: '+91 95432 66554',
    },
    notes: 'Heavy structural steel welding specialist.',
    rating: 4.95,
    completedJobs: 51,
    currentStatus: 'Available',
    verificationStatus: 'Verified',
    documents: {
      photo: true,
      aadhaarCard: true,
      certificates: true,
    },
    registeredAt: '2024-09-18',
  },
  {
    id: 'WKR-1005',
    fullName: 'Anurag Sharma',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80',
    phoneNumber: '+91 94321 09876',
    aadhaarNumber: 'XXXX-XXXX-1109',
    village: 'Solan',
    district: 'Solan',
    state: 'Himachal Pradesh',
    skill: 'Carpentry',
    subSkill: 'Shuttering & Formwork Specialist',
    experienceYears: 4,
    languages: ['Hindi', 'Pahari'],
    dailyWage: 800,
    availability: false,
    emergencyContact: {
      name: 'Kavita Sharma',
      relationship: 'Wife',
      phone: '+91 94321 22334',
    },
    notes: 'Good understanding of blueprint drawings for formwork.',
    rating: 4.6,
    completedJobs: 18,
    currentStatus: 'Assigned',
    verificationStatus: 'Verified',
    documents: {
      photo: true,
      aadhaarCard: true,
      certificates: true,
    },
    registeredAt: '2025-03-10',
  },
  {
    id: 'WKR-1006',
    fullName: 'Santosh Yadav',
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    phoneNumber: '+91 93210 98765',
    aadhaarNumber: 'XXXX-XXXX-7762',
    village: 'Jaunpur',
    district: 'Jaunpur',
    state: 'Uttar Pradesh',
    skill: 'Logistics',
    subSkill: 'Warehouse Loader / Forklift Operator',
    experienceYears: 3,
    languages: ['Hindi'],
    dailyWage: 750,
    availability: true,
    emergencyContact: {
      name: 'Rambriksh Yadav',
      relationship: 'Father',
      phone: '+91 93210 44556',
    },
    notes: 'Active worker, capable of handling heavy cargo loads.',
    rating: 4.5,
    completedJobs: 24,
    currentStatus: 'Available',
    verificationStatus: 'Pending',
    documents: {
      photo: true,
      aadhaarCard: true,
      certificates: false,
    },
    registeredAt: '2026-06-15',
  }
];

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'CMP-2001',
    companyName: 'L&T Infrastructure Construtec Ltd',
    gstNumber: '07AAAAA0000A1Z5',
    industry: 'Construction & Civil Works',
    officeAddress: 'Sector 62, Cyber Park, Noida, UP - 201309',
    contactPerson: 'Vikrant Deshmukh (HR Head)',
    phone: '+91 98112 34567',
    email: 'hr@ltconst.com',
    status: 'Active',
    subscriptionPlan: 'Enterprise',
    hiringHistoryCount: 142,
    totalSpent: 1850000,
    joinedDate: '2024-05-10',
  },
  {
    id: 'CMP-2002',
    companyName: 'BuildCon Logistics & Warehousing',
    gstNumber: '09BBBBA1111B2Z8',
    industry: 'Logistics & Supply Chain',
    officeAddress: 'Expressway Hub, Greater Noida, UP',
    contactPerson: 'Megha Singhania',
    phone: '+91 98776 54321',
    email: 'hiring@buildcon.in',
    status: 'Active',
    subscriptionPlan: 'Pro',
    hiringHistoryCount: 78,
    totalSpent: 920000,
    joinedDate: '2024-08-22',
  },
  {
    id: 'CMP-2003',
    companyName: 'Metro Rail Metal Fabricators',
    gstNumber: '06CCCCA2222C3Z2',
    industry: 'Heavy Engineering & Manufacturing',
    officeAddress: 'Industrial Area Phase 2, Faridabad, Haryana',
    contactPerson: 'Rajesh Khanna',
    phone: '+91 99988 77665',
    email: 'projects@metrometals.co.in',
    status: 'Active',
    subscriptionPlan: 'Enterprise',
    hiringHistoryCount: 95,
    totalSpent: 1340000,
    joinedDate: '2024-10-01',
  },
  {
    id: 'CMP-2004',
    companyName: 'Apex Solar Energy Solutions',
    gstNumber: '08DDDDD3333D4Z9',
    industry: 'Renewable Energy',
    officeAddress: 'Bhiwadi Industrial Estate, Rajasthan',
    contactPerson: 'Amitabh Joshi',
    phone: '+91 98223 34455',
    email: 'admin@apexsolar.org',
    status: 'Pending Approval',
    subscriptionPlan: 'Basic',
    hiringHistoryCount: 0,
    totalSpent: 0,
    joinedDate: '2026-07-28',
  }
];

export const INITIAL_REQUESTS: WorkerRequest[] = [
  {
    id: 'REQ-5001',
    companyId: 'CMP-2001',
    companyName: 'L&T Infrastructure Construtec Ltd',
    skillRequired: 'Construction',
    subSkill: 'Mason / Bricklayer',
    numberOfWorkers: 5,
    assignedWorkerIds: ['WKR-1001'],
    location: 'Metro Site Phase 4, Botanical Garden, Noida',
    reportingDate: '2026-08-08',
    reportingTime: '08:00 AM',
    durationDays: 14,
    dailyWageOffered: 900,
    foodProvided: true,
    accommodationProvided: true,
    transportationProvided: true,
    genderPreference: 'Any',
    experienceRequiredYears: 4,
    remarks: 'Must carry safety helmet and boots. Overtime allowance provided.',
    priority: 'Urgent',
    workflowStatus: 'Workers Assigned',
    createdAt: '2026-08-01',
  },
  {
    id: 'REQ-5002',
    companyId: 'CMP-2002',
    companyName: 'BuildCon Logistics & Warehousing',
    skillRequired: 'Logistics',
    subSkill: 'Warehouse Loader / Forklift Operator',
    numberOfWorkers: 8,
    assignedWorkerIds: ['WKR-1006'],
    location: 'Warehouse Hub 3, Surajpur, Greater Noida',
    reportingDate: '2026-08-10',
    reportingTime: '09:00 AM',
    durationDays: 30,
    dailyWageOffered: 800,
    foodProvided: true,
    accommodationProvided: false,
    transportationProvided: true,
    genderPreference: 'Male',
    experienceRequiredYears: 2,
    remarks: 'Night shift rotation may be required.',
    priority: 'Normal',
    workflowStatus: 'Searching Workers',
    createdAt: '2026-08-03',
  },
  {
    id: 'REQ-5003',
    companyId: 'CMP-2003',
    companyName: 'Metro Rail Metal Fabricators',
    skillRequired: 'Welding',
    subSkill: 'ARC & TIG Structural Welder',
    numberOfWorkers: 3,
    assignedWorkerIds: ['WKR-1004'],
    location: 'Yard 12, Ballabhgarh, Faridabad',
    reportingDate: '2026-08-06',
    reportingTime: '07:30 AM',
    durationDays: 7,
    dailyWageOffered: 1250,
    foodProvided: true,
    accommodationProvided: true,
    transportationProvided: true,
    genderPreference: 'Any',
    experienceRequiredYears: 5,
    remarks: 'High accuracy welding certification preferred.',
    priority: 'High',
    workflowStatus: 'Workers Confirmed',
    createdAt: '2026-08-02',
  }
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'ATT-901',
    workerId: 'WKR-1001',
    workerName: 'Ramesh Kumar',
    companyId: 'CMP-2001',
    companyName: 'L&T Infrastructure Construtec Ltd',
    requestId: 'REQ-5001',
    date: '2026-08-05',
    checkIn: '07:55 AM',
    checkOut: '05:05 PM',
    status: 'Present',
  },
  {
    id: 'ATT-902',
    workerId: 'WKR-1002',
    workerName: 'Suresh Patel',
    companyId: 'CMP-2003',
    companyName: 'Metro Rail Metal Fabricators',
    requestId: 'REQ-5003',
    date: '2026-08-05',
    checkIn: '08:15 AM',
    checkOut: '05:30 PM',
    status: 'Late',
  },
  {
    id: 'ATT-903',
    workerId: 'WKR-1005',
    workerName: 'Anurag Sharma',
    companyId: 'CMP-2001',
    companyName: 'L&T Infrastructure Construtec Ltd',
    requestId: 'REQ-5001',
    date: '2026-08-05',
    checkIn: '08:00 AM',
    checkOut: '01:00 PM',
    status: 'Half Day',
  }
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: 'INV-2026-0801',
    companyId: 'CMP-2001',
    companyName: 'L&T Infrastructure Construtec Ltd',
    requestId: 'REQ-5001',
    amount: 126000,
    billingPeriod: 'Jul 15, 2026 - Jul 31, 2026',
    wageType: 'Weekly',
    status: 'Paid',
    dueDate: '2026-08-05',
    paidDate: '2026-08-04',
  },
  {
    id: 'INV-2026-0802',
    companyId: 'CMP-2002',
    companyName: 'BuildCon Logistics & Warehousing',
    requestId: 'REQ-5002',
    amount: 84000,
    billingPeriod: 'Jul 01, 2026 - Jul 30, 2026',
    wageType: 'Monthly',
    status: 'Pending',
    dueDate: '2026-08-12',
  },
  {
    id: 'INV-2026-0803',
    companyId: 'CMP-2003',
    companyName: 'Metro Rail Metal Fabricators',
    requestId: 'REQ-5003',
    amount: 52500,
    billingPeriod: 'Jul 20, 2026 - Jul 27, 2026',
    wageType: 'Daily',
    status: 'Paid',
    dueDate: '2026-07-30',
    paidDate: '2026-07-29',
  }
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'NOTIF-1',
    title: 'New Worker Request Submitted',
    message: 'BuildCon Logistics submitted a request for 8 Warehouse Loaders.',
    recipientRole: 'admin',
    timestamp: '10 minutes ago',
    read: false,
    type: 'info',
  },
  {
    id: 'NOTIF-2',
    title: 'Workers Assigned to Your Site',
    message: '5 Masons have been assigned to your Metro Site project.',
    recipientRole: 'company',
    companyId: 'CMP-2001',
    timestamp: '1 hour ago',
    read: false,
    type: 'success',
  },
  {
    id: 'NOTIF-3',
    title: 'Payment Confirmed',
    message: 'Payment of ₹1,26,000 received from L&T Infrastructure.',
    recipientRole: 'admin',
    timestamp: '3 hours ago',
    read: true,
    type: 'success',
  }
];

export const SKILL_CATEGORIES = [
  { name: 'Construction', subSkills: ['Mason / Bricklayer', 'Concrete Finisher', 'Scaffolder', 'Bar Bender / Steel Fixer'] },
  { name: 'Electrical', subSkills: ['Industrial Wiring Technician', 'Substation Operator', 'Cable Jointer', 'Maintenance Electrician'] },
  { name: 'Plumbing', subSkills: ['Pipe Fitter / Drainage Specialist', 'Sanitary Installer', 'Firefighting Pipeline Fitter'] },
  { name: 'Welding', subSkills: ['ARC & TIG Structural Welder', 'MIG Welder', 'Pipeline Gas Welder'] },
  { name: 'Carpentry', subSkills: ['Shuttering & Formwork Specialist', 'Furniture Woodworker', 'Interior Decorator'] },
  { name: 'Logistics', subSkills: ['Warehouse Loader / Forklift Operator', 'Packer & Dispatch Assistant', 'Inventory Helper'] }
];
